#!/usr/bin/env bash
~/Tools/pandoc/pandoc.exe --standalone -c style.css --from markdown --to html -o index.html index.md && ~/Tools/wkhtmltopdf/bin/wkhtmltopdf --enable-local-file-access index.html ~/Documents/resume.pdf
